version: '3'
services:
  mldocker:
    container_name: mldocker
    build: .
    command: bash -c "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"
    volumes:
      - ./notebooks:/jupyter
    ports:
      - 8888:8888
    restart: always
    environment:
      - PYTOHNBUFFERED=1
      - NOTEBOOK_PWD=mldocker
